name: Go Linter
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  golangci:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22'
      - uses: actions/checkout@v3          
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v0.0.2
          only-new-issues: true